name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: example.com # Replace with your remote host
          username: ${{ secrets.SSH_USERNAME }} # Store your SSH username as a secret
          password: ${{ secrets.SSH_PASSWORD }} # Store your SSH password as a secret
          port: 22 # Replace with your SSH port
          script: |
            echo "Today is Dec 12, 2023, I'm happt to see you all" > /var/www/html/index.html


            
            

